### ISSUE TITLE
Watch saying virtual key not set up

### ISSUE THREAD

**Issue by jasmee1979** [itsMeDavidV/Watchla-Support#210]
Since running the latest update the watch app and iOS app are both saying that the virtual key is not setup but it is and is working

**Comment by Z3bulon** [comment]
Same issue on my side. And I have bought the WatchLA app.
I am the sole driver of this company car.
Any solution to get this virtual key ?

BR
Jean-Jacques

**Comment by backblunt** [comment]
I too have this problem. I got the virtual key to work (I can now use my watch to control the car) but I still get the message on the phone app and on my watch that says I’ve not setup my virtual key. It’s annoying. Also, when I open the watch app, rather than defaulting to the car controls screen, it starts on the charging screen. I have to click the little “x” to get to the controls screen (which, at this time it tells me that I need to setup my virtual key, so I have to scroll down to get to the car controls).

**Comment by jasmee1979** [comment]
I have tried deleting and re-installing the Tesla IOS app, the Watchla IOS app and the Watchla watch app but this didn’t resolve the issue. Both the Watchla iOS and watch apps still show as virtual key not set up. It is.

I am able to use the watch app and the functions work, albeit the connectivity seems a little delayed. Would be great to get a fix for this ASAP.

**Comment by olmeijer23** [comment]
Same issue here.

**Comment by marksahagun** [comment]
Same.

**Comment by itsMeDavidV** [comment]
Hi everyone, please update to v3.5.2 as this issue has been addressed and fixed!

**Comment by jasmee1979** [comment]
Hi

I am running v3.5.2 and the issue still exists.

Kind regards

Jason Meek
________________________________

**Comment by olmeijer23** [comment]
Same for me. Nothing changed after the upgrade. Issue persists.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: jasmee1979 ***@***.***>
Verzonden: Friday, January 19, 2024 12:45:13 AM
Aan: itsMeDavidV/Watchla-Support ***@***.***>
CC: Onno Meijer ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [itsMeDavidV/Watchla-Support] Watch saying virtual key not set up (Issue #210)


Hi

I am running v3.5.2 and the issue still exists.

Kind regards

Jason Meek
________________________________

**Comment by raytong101** [comment]
im on v3.5.3 and is still the same. this is annoying

**Comment by olmeijer23** [comment]
Same here on v3.5.3 keeps asking for Virtual key setup, even after reconnecting. Also goes directly to the Charge Stats screen on watch.

**Comment by CassandraMarie** [comment]
Hi @olmeijer23, @raytong101, @backblunt, @jasmee1979, and @Z3bulon, we apologize for the late reply. Are you still experiencing this issue?

**Comment by jasmee1979** [comment]
For me the virtual key now works intermittently at best. I continuously have to re-authorise the watch.

The app has become completely unusable as the commands either fail to send or take ages to complete. I have lost count how many times I have been caught out by the boot door closing on me because the app took so long to send the open command I had already opened it manually and the app then executes and reverses the command so it closes on me. This has nearly trapped my kids numerous times. It’s dangerous.

**Comment by CassandraMarie** [comment]
Hi @jasmee1979, We apologize for the inconvenience Watchla has caused. We have been actively working to improve Watchla and we would love to find a solution for you. To better assist you, could you please verify which version of Watchla you are currently using? You can check the version of both your iOS and watchOS by navigating to preferences and scrolling to the bottom of the screen. The latest version is 3.8.

**Comment by jasmee1979** [comment]
I am using 3.8.1 on both iOS and WatchOS.

**Comment by CassandraMarie** [comment]
@jasmee1979, Can you send over your support code [https://watchla.app/contact/](https://watchla.app/contact/) so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code
Please be sure to link to this issue when you reach out.

**Comment by jasmee1979** [comment]
Done
