### ISSUE TITLE
3.5.2 Batterij State widget not updating

### ISSUE THREAD

**Issue by Gr1ss0m** [itsMeDavidV/Watchla-Support#229]
Hello,

i have on my iPhone and watch version 3.5.2. 
I use the battery state widget but it is not updating. 
wenn I click on it it does however show the actual values. 
Also in the Watchla app on my iPhone the values are correct. 
I tried signing in and out but this did not help.

**Comment by yoshiat** [comment]
+1

**Comment by claire078** [comment]
Battery companion works to me, bur Relevant vehicle information just blank.

**Comment by yoshiat** [comment]
@itsMeDavidV I believe this is fixed with 3.5.3.

**Comment by volcomboy62** [comment]
I’m in version 3.5.3 and it’s not fixed
My widget on my Apple Watch is not refresh with the correct data

**Comment by merovx** [comment]
Nothing fixed with version 3.5.3 (332) On Apple Watch Series 9
