### ISSUE TITLE
No commands work

### ISSUE THREAD

**Issue by Ianhed** [itsMeDavidV/Watchla-Support#290]
The last couple of weeks has been very demanding as a Watchla user. Constant disruption with the very update. I can’t remember how many times I’ve logged in and out. Verified my Tesla account. Reinstalled the app and so on.

The latest is that no commands work anymore. The account is verified and the app has access to my car but nothing works. See error message in added file. 
![IMG_0119](https://github.com/itsMeDavidV/Watchla-Support/assets/159637744/cf247be6-b149-4428-8e71-0dee6405c515)

**Comment by itsMeDavidV** [comment]
Hi @Ianhed this error states that your device lost internet connection while sending the command. See "The network connection was lost"

**Comment by Ianhed** [comment]
Thanks for your reply! Strange, but there nothing wrong with my connection on my phone and Apple Watch. 

Also the Tesla app works just fine.

**Comment by itsMeDavidV** [comment]
Hm, could be a dropped connection then. Nonetheless we investigate and found that for some regions commands were being sent to the wrong region. We fixed that and Apple is reviewing now. Thanks for reporting!

**Comment by itsMeDavidV** [comment]
Hi @Ianhed update v3.6.3 is now available to download on the App Store

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
